on:
  push:
    branches:
      - "main"
      - "dev"
      - "úprava-workflow-pro-main-a-dev"
env:
  branch: main
 - pwsh: |
    If (github.master_branch == "úprava-workflow-pro-main-a-dev") {
      env.branch = dev
    }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: |
          export CURRENT_DIR=`pwd`
          cd $CURRENT_DIR
          echo "CURRENT_DIR=$CURRENT_DIR" >> $GITHUB_ENV
          sudo apt install -y nodejs npm  && sudo pip install yq
          sudo npm install -g @angular/cli

      - name: Build
        run: |
          npm ci
          ng build --configuration production

      - name: List Files in Distribution Directory
        run: ls -R ./dist

      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.CD_FTP_SERVER }}
          user: ${{ secrets.CD_FTP_USERNAME }}
          password: ${{ secrets.CD_FTP_PASSWORD }}
          local_dir: "./dist/webovky"
          remote_dir: "./www/$(env)"
          delete: "false"
